on: [push]

permissions:
  id-token: write

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Hello world action step
        id: hello
        uses: coauthor-app/capture-action@a91fbbf9bc4d9c50ee450fba8fff81d01930cef6
        with:
          evidence: 'system-verification'
          type: 'bdd'
          format: 'serenity'
          hostname: 'vrhs2uv136.execute-api.eu-west-2.amazonaws.com'
          path: 'reports/**'


