on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: coauthor-app/capture-action@e0e7635b6f9827a88204795f2357583b2e588b4b
        with:
          evidence: 'system-verification'
          type: 'bdd'
          format: 'serenity'
          hostname: 'vrhs2uv136.execute-api.eu-west-2.amazonaws.com'
          path: /reports/**


