on: [push]

permissions:
  id-token: write

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: coauthor-app/capture-action@main
        with:
          evidence: 'system-verification'
          type: 'bdd'
          format: 'serenity'
          hostname: 'vrhs2uv136.execute-api.eu-west-2.amazonaws.com'
          path: reports/file1.txt


